// AI 编程工具竞品分析 · 数据快照（单一数据源）
// 所有价格均为官方页面 2026-09-27 抓取核实的 USD 标价，未做汇率换算。
// null = 未公开/未核实；不编造数据。每条关键数据通过 src 关联 sources。
const REPORT = {
  meta: {
    title: "AI 编程工具竞品分析与团队采购成本报表",
    snapshotDate: "2026-09-27",
    currency: "USD",
    currencyNote: "全部价格为美元（USD）官方标价，未做汇率换算；不含税。",
    method: "直接抓取官方定价页与帮助文档 HTML 快照；搜索摘要仅用于定位来源。",
    gapNote: "Cursor 年付价、Windsurf Teams 席位包含关系、Copilot 年付价与 premium 请求固定额度、Claude Code 具体用量上限、Gemini 个人免费额度未能在本次快照页面核实，均标注为待核实。",
  },
  sources: {
    cursor:      { title: "Cursor — Pricing", url: "https://cursor.com/pricing", date: "2026-09-27", pubDate: null },
    cursorDocs:  { title: "Cursor Docs — Pricing & Usage", url: "https://docs.cursor.com/account/pricing", date: "2026-09-27", pubDate: null, note: "本次未抓取到正文，仅引用定价页自述" },
    copilot:     { title: "GitHub Copilot — Plans & pricing", url: "https://github.com/features/copilot/plans", date: "2026-09-27", pubDate: null },
    claude:      { title: "Claude — Pricing (Anthropic)", url: "https://claude.com/pricing", date: "2026-09-27", pubDate: null },
    codexHelp:   { title: "OpenAI Help — Codex in ChatGPT", url: "https://help.openai.com/en/articles/11369540-codex-in-chatgpt", date: "2026-09-27", pubDate: null },
    codexProPause:{ title: "OpenAI Help — Pro 计划暂停公告（页面横幅，指引 article 9793128）", url: "https://help.openai.com/en/articles/11369540-codex-in-chatgpt", date: "2026-09-27", pubDate: null },
    windsurf:    { title: "Windsurf / Cognition — Plans and Pricing（页面现以 Devin 品牌呈现）", url: "https://windsurf.com/pricing", date: "2026-09-27", pubDate: null },
    gemini:      { title: "Gemini Code Assist — Pricing", url: "https://codeassist.google.com/pricing", date: "2026-09-27", pubDate: null },
  },
  tools: [
    {
      id: "cursor", name: "Cursor", vendor: "Anysphere",
      positioning: "AI 原生 IDE（VS Code 分支）+ 终端 CLI + 云端 Agent，Agent 为核心卖点",
      forms: ["桌面 IDE（macOS/Windows/Linux）", "终端 CLI", "云端 Agent（Cloud Agents）"],
      usageModel: "每档包含一定模型用量；超出后按量计费（on-demand），账单后付（billed in arrears）",
      plans: [
        { name: "Hobby", audience: "个人", monthly: 0, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true,
          included: "有限 Agent 请求", overage: null, src: "cursor" },
        { name: "Pro", audience: "个人", monthly: 20, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true,
          included: "Agent 用量上限高于免费版；Grok 限额较宽松；含云 Agent", overage: "按量计费（后付）", src: "cursor" },
        { name: "Pro+", audience: "个人", monthly: 60, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true,
          included: "面向每日使用 Agent 的用户", overage: "按量计费（后付）", src: "cursor" },
        { name: "Ultra", audience: "个人", monthly: 200, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true,
          included: "面向 Agent 重度用户", overage: "按量计费（后付）", src: "cursor" },
        { name: "Teams", audience: "团队", monthly: 40, annualMonthly: null, annualUpfront: null, minSeats: null, perSeat: true, purchasable: true,
          included: "集中计费与管理、团队规则/技能/插件市场、云 Agent 自动化、Bugbot 代码审查、用量分析、团队隐私模式",
          overage: "按量计费（后付）", src: "cursor" },
        { name: "Premium（Teams）", audience: "团队", monthly: null, annualMonthly: null, annualUpfront: null, minSeats: null, perSeat: true, purchasable: true,
          included: "Teams 全部功能 + 用量池化（pooled usage）+ 发票/PO 计费 + SCIM 席位管理", overage: null, src: "cursor", note: "价格未公开，需向官方获取" },
        { name: "Enterprise", audience: "团队", inquiry: true, monthly: null, purchasable: false,
          included: "面向需要发票计费、池化用量或高级安全的大型组织", src: "cursor" },
      ],
      capabilities: {
        completion: { s: "full", note: "IDE 内置补全" },
        repoUnderstanding: { s: "full", note: "代码库索引与上下文" },
        multiFile: { s: "full", note: "Agent 多文件修改" },
        terminal: { s: "full", note: "终端执行（IDE 终端 + CLI）" },
        review: { s: "full", note: "Bugbot 智能代码审查（Teams 含，个人按用量计费）" },
        cloudAgent: { s: "full", note: "Cloud Agents；Teams 提供团队共享上下文自动化" },
      },
      admin: {
        sso: { s: "ent", note: "企业级 SSO 属 Enterprise 档；Teams Premium 含 SCIM 席位管理" },
        audit: { s: "ent", note: "未见公开说明（页面提及 Admin Dashboard 用量分析）" },
        privacyMode: { s: "full", note: "团队隐私模式：开启后代码数据不用于训练（官方保证）" },
        adminDashboard: { s: "full", note: "管理员可查看用量与关键指标" },
      },
      recent90d: ["定价页现推荐 Pro+（日常 Agent 用户）与 Ultra（重度用户）；页面强调仅通过官网直售、无授权转售商。"],
      calc: { teamPlan: "Teams", monthlyPrice: 40, annualMonthly: null, minSeats: null, seatNote: "按席位计价，页面未标注最低席位数" },
    },
    {
      id: "copilot", name: "GitHub Copilot", vendor: "GitHub / Microsoft",
      positioning: "原生集成 GitHub 生态的编程助手，覆盖 IDE/CLI/GitHub.com/移动端，企业治理最成熟",
      forms: ["IDE 插件（VS Code/JetBrains/Visual Studio/Vim/Neovim）", "GitHub CLI / Copilot CLI", "GitHub.com 内置（代码审查、Agent）", "GitHub Mobile"],
      usageModel: "GitHub AI Credits：1 credit = $0.01；各档含每月额度，可设美元预算，用完自动继续并按额度扣减（$10 预算 ≈ 1,000 credits）",
      plans: [
        { name: "Free", audience: "个人", monthly: 0, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true,
          included: "每月 2,000 次补全 + 50 次聊天（含 Copilot Edits）", overage: null, src: "copilot" },
        { name: "Pro", audience: "个人", monthly: 10, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true,
          included: "不限量补全与聊天，含 premium 请求额度", overage: "超出 premium 额度后按 GitHub AI Credits 扣费", src: "copilot",
          note: "年付 $100/年 为公开常见价，本次快照页面未直接核实 → 待核实" },
        { name: "Pro+", audience: "个人", monthly: 39, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true,
          included: "更高 premium 请求额度与模型选择", overage: "按 GitHub AI Credits 扣费", src: "copilot" },
        { name: "Business", audience: "团队", monthly: 19, annualMonthly: null, annualUpfront: null, minSeats: null, perSeat: true, purchasable: true,
          included: " license/策略管理、IP 赔偿、组织级用量与策略管控", overage: "管理员设定额度与是否允许额外付费用量", src: "copilot" },
        { name: "Enterprise", audience: "团队", monthly: 39, annualMonthly: null, annualUpfront: null, minSeats: null, perSeat: true, purchasable: true,
          included: "Business 全部 + 代码库索引检索、微调模型、更多治理层", overage: "同 Business", src: "copilot" },
      ],
      capabilities: {
        completion: { s: "full", note: "IDE 内联补全，免费档也含" },
        repoUnderstanding: { s: "full", note: "Enterprise 含代码库索引；其余档位上下文较弱" },
        multiFile: { s: "full", note: "Agent 模式多文件修改（含 GitHub.com）" },
        terminal: { s: "full", note: "Copilot CLI + GitHub CLI 集成" },
        review: { s: "full", note: "GitHub Copilot 代码审查（PR 评审）" },
        cloudAgent: { s: "full", note: "GitHub.com 云端 Agent（issue→PR）" },
      },
      admin: {
        sso: { s: "ent", note: "随 GitHub 组织体系（SAML SSO 属 GitHub Enterprise 能力）" },
        audit: { s: "ent", note: "组织审计日志随 GitHub Enterprise" },
        privacyMode: { s: "full", note: "Business/Enterprise 数据不用于训练模型（官方承诺）" },
        adminDashboard: { s: "full", note: "组织策略、用量限制、premium 额度管理" },
      },
      recent90d: ["GitHub AI Credits 新计费口径（1 credit=$0.01，按预算购买，$10≈1,000 credits）已替代旧的 premium request 计费叙述；具体 premium 额度数字未在快照页面核实。"],
      calc: { teamPlan: "Business", monthlyPrice: 19, annualMonthly: null, minSeats: null, seatNote: "按用户/月计价；最低席位未在快照页核实" },
    },
    {
      id: "claude", name: "Claude Code（含于 Claude 订阅）", vendor: "Anthropic",
      positioning: "终端优先的 Agent 编码工具，随 Claude 订阅（Pro/Max/Team/Enterprise）提供，可与聊天共用额度池",
      forms: ["终端 CLI", "IDE 扩展（VS Code/JetBrains）", "Desktop 应用", "GitHub/GitLab 集成（读 issue、写代码、跑测试、开 PR）"],
      usageModel: "订阅共享额度池（终端工作与聊天同池）；按 5 小时会话 + 周窗口限制；重度编码可切换为 API 按量付费（Console）",
      plans: [
        { name: "Free", audience: "个人", monthly: 0, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true, included: "基础聊天，少量用量", src: "claude" },
        { name: "Pro", audience: "个人", monthly: 20, annualMonthly: 17, annualUpfront: 204, minSeats: 1, purchasable: true,
          included: "含 Claude Code、Projects、更多模型；周用量限制（约为 Max 的 1/5）", overage: "可切换 API 按量付费", src: "claude",
          annualNote: "年付 $200 一次付清（折合 $17/月）；月付 $20" },
        { name: "Max 5x", audience: "个人", monthly: 100, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true,
          included: "5× Pro 用量（每 5 小时会话）", overage: null, src: "claude" },
        { name: "Max 20x", audience: "个人", monthly: 200, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true,
          included: "20× Pro 用量", overage: null, src: "claude" },
        { name: "Team Standard", audience: "团队", monthly: 25, annualMonthly: 20, annualUpfront: 240, minSeats: null, perSeat: true, purchasable: true,
          included: "团队协作 + 管理；席位费 + 按模型/任务的用量费（API 费率）", overage: "用量按 API 费率另计", src: "claude",
          annualNote: "年付 $20/席/月；月付 $25/席/月" },
        { name: "Team Premium", audience: "团队", monthly: 125, annualMonthly: 100, annualUpfront: 1200, minSeats: null, perSeat: true, purchasable: true,
          included: "Team 全部 + 更高用量", overage: "用量按 API 费率另计", src: "claude",
          annualNote: "年付 $100/席/月；月付 $125/席/月" },
        { name: "Enterprise", audience: "团队", monthly: 20, annualMonthly: 20, annualUpfront: 240, minSeats: null, perSeat: true, purchasable: true,
          included: "Team 全部 + SCIM、审计日志、自定义数据保留、RBAC；席位费 + API 费率用量，按年计费", overage: "用量按 API 费率另计", src: "claude",
          annualNote: "$20/席/月 + API 费率用量（页面 FAQ 自述）" },
      ],
      capabilities: {
        completion: { s: "none", note: "非补全型工具（终端 Agent，非 IDE 内联补全）" },
        repoUnderstanding: { s: "full", note: "代码库级 Agent 上下文" },
        multiFile: { s: "full", note: "多文件修改核心能力" },
        terminal: { s: "full", note: "终端执行为核心形态" },
        review: { s: "full", note: "GitHub/GitLab 集成：读 issue、跑测试、开 PR" },
        cloudAgent: { s: "partial", note: "云端任务形态未在快照页面说明 → 待核实" },
      },
      admin: {
        sso: { s: "ent", note: "Enterprise 含 SCIM/SSO" },
        audit: { s: "ent", note: "Enterprise 含审计日志、自定义数据保留、RBAC" },
        privacyMode: { s: "partial", note: "数据使用说明在页面分层描述；具体训练政策未在快照摘录" },
        adminDashboard: { s: "full", note: "Team/Enterprise 管理控制台" },
      },
      recent90d: [
        "Team/Enterprise 改为「席位费 + API 费率用量」混合计费（Team Standard $20/席/月年付 + 用量），成本结构从固定订阅转向订阅+用量。",
        "Team Premium 档出现（$100/席/月年付 / $125 月付）。",
        "Claude Enterprise 定价公开化为 $20/席/月 + API 用量（FAQ 自述）。",
      ],
      calc: { teamPlan: "Team Standard", monthlyPrice: 25, annualMonthly: 20, minSeats: null, seatNote: "最低席位数未在快照页核实；注意用量费另计，本计算器仅算席位费" },
    },
    {
      id: "codex", name: "OpenAI Codex（含于 ChatGPT）", vendor: "OpenAI",
      positioning: "云端 + 本地混合的编码 Agent，随 ChatGPT 订阅提供；本地任务跑在用户设备，云端任务跑在 OpenAI 托管环境",
      forms: ["终端 CLI（Codex CLI）", "IDE 扩展", "ChatGPT 桌面应用", "云端任务（Codex Cloud）", "GitHub 代码审查集成"],
      usageModel: "按 5 小时 + 周窗口限制；推荐好友可获得可积累的限速重置（banked reset）；具体任务数额度未在快照页公开",
      plans: [
        { name: "Free（ChatGPT）", audience: "个人", monthly: 0, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true, included: "有限 Codex 使用", src: "codexHelp" },
        { name: "Plus（ChatGPT）", audience: "个人", monthly: 20, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true,
          included: "Codex（本地+云端）", overage: "可购买 credits 继续使用", src: "codexHelp",
          note: "$20/月为 ChatGPT 公开常见价，本次快照页面未直接核实 → 待核实" },
        { name: "Pro（ChatGPT）", audience: "个人", monthly: 200, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: false,
          included: "最高档个人用量", overage: null, src: "codexProPause",
          note: "重要：官方横幅公告（2026-09-10 起）新注册与升级至 Pro $200 已暂停，存量订阅照常续费 → 新采购无法下单" },
        { name: "Business / Enterprise / Edu（ChatGPT）", audience: "团队", inquiry: true, monthly: null, purchasable: false,
          included: "组织级管理；价格未公开", src: "codexHelp" },
      ],
      capabilities: {
        completion: { s: "none", note: "非补全型工具（Agent 形态）" },
        repoUnderstanding: { s: "full", note: "云端任务读取仓库；本地任务在用户设备运行" },
        multiFile: { s: "full", note: "Agent 多文件修改" },
        terminal: { s: "full", note: "Codex CLI + 桌面工作流" },
        review: { s: "full", note: "云端任务可产出 PR；代码审查集成待核实" },
        cloudAgent: { s: "full", note: "Codex Cloud 委派云任务；Codex Local 覆盖 CLI/IDE/桌面" },
      },
      admin: {
        sso: { s: "ent", note: "Business/Enterprise 档提供组织管理；细节未在快照页公开" },
        audit: { s: "unknown", note: "未找到说明" },
        privacyMode: { s: "partial", note: "数据控制随 ChatGPT 训练数据设置；工作区可分别管控本地/云端任务" },
        adminDashboard: { s: "partial", note: "托管工作区（Managed workspace）可分别控制本地与云任务" },
      },
      recent90d: [
        "2026-09-10 起：ChatGPT Pro $200 档暂停新注册与升级（存量可续费）——对按需采购是硬约束。",
        "Codex 限速重置机制：推荐好友可获得 banked rate-limit reset，可刷新 5 小时与周窗口。",
      ],
      calc: { teamPlan: null, monthlyPrice: null, annualMonthly: null, minSeats: null,
        seatNote: "团队方案（Business/Enterprise/Edu）需询价，价格未公开 → 本计算器无法给出有效报价" },
    },
    {
      id: "windsurf", name: "Windsurf（Cognition / Devin）", vendor: "Cognition AI",
      positioning: "已并入 Cognition（Devin 母公司）：IDE + 云 Agent（Devin）统一套餐；定价页现以 Devin 品牌呈现",
      forms: ["桌面 IDE（Windsurf Editor）", "CLI（Devin CLI）", "云端 Agent（Devin Cloud）", "Slack / Teams 集成（高阶档）"],
      usageModel: "每日/每周自动刷新的用量额度；多数用户够用；超出后可按 API 价格购买额外用量",
      plans: [
        { name: "Free", audience: "个人", monthly: 0, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true,
          included: "轻量 Agent 额度、模型选择有限、不限量内联编辑与 Tab 补全", overage: null, src: "windsurf" },
        { name: "Pro", audience: "个人", monthly: 20, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true,
          included: "更高额度、OpenAI/Claude/Gemini 等前沿模型、云 Agent（Devin Cloud）；SWE 模型在 Devin Desktop/CLI 限时免费（至 2026-10-10）",
          overage: "按 API 价格购买额外用量", src: "windsurf" },
        { name: "Max", audience: "个人", monthly: 200, annualMonthly: null, annualUpfront: null, minSeats: 1, purchasable: true,
          included: "Pro 全部 + 显著更高额度", overage: "按 API 价格", src: "windsurf" },
        { name: "Teams", audience: "团队", monthly: 80, annualMonthly: null, annualUpfront: null, minSeats: null, perSeat: true, purchasable: true,
          included: "团队套餐基础费 $80/月 + 每个完整开发席位 $40/月；集中计费；上限 200 用户",
          overage: "按 API 价格", src: "windsurf",
          note: "$80 基础费是否含席位、席位构成未在页面明确 → 待核实；计算器按 $80 + $40×N 估算并在计算过程标注" },
        { name: "Enterprise", audience: "团队", inquiry: true, monthly: null, purchasable: false,
          included: "集中企业管理控制、多组织管理、Teamspace 隔离", src: "windsurf" },
      ],
      capabilities: {
        completion: { s: "full", note: "不限量 Tab 补全与内联编辑（免费档也含）" },
        repoUnderstanding: { s: "full", note: "IDE 级上下文 + Devin 云 Agent" },
        multiFile: { s: "full", note: "Agent 多文件修改" },
        terminal: { s: "full", note: "CLI + 桌面工作流" },
        review: { s: "partial", note: "代码审查能力未在快照页说明 → 待核实" },
        cloudAgent: { s: "full", note: "Devin Cloud 云 Agent；Pro 起可用" },
      },
      admin: {
        sso: { s: "ent", note: "Enterprise 档提供集中管理" },
        audit: { s: "unknown", note: "未找到说明" },
        privacyMode: { s: "unknown", note: "未找到说明" },
        adminDashboard: { s: "ent", note: "Enterprise 集中管理控制；Teams 仅集中计费" },
      },
      recent90d: [
        "重大变化：Windsurf 定价页现以 Cognition「Devin」品牌呈现，Pro $20/月、Max $200/月、Teams $80/月+$40/席/月 —— 采购时应以 Cognition 统一合同为准。",
        "SWE 模型在 Devin Desktop/CLI 限时免费至 2026-10-10。",
      ],
      calc: { teamPlan: "Teams", monthlyPrice: 80, perSeat: 40, annualMonthly: null, minSeats: null,
        seatNote: "计算公式：$80 基础 + $40×席位数；上限 200 用户；年付价未公开" },
    },
    {
      id: "gemini", name: "Gemini Code Assist", vendor: "Google",
      positioning: "Google 生态的企业级代码助手（Gemini 3，1M token 上下文），按席位订阅，月付/年付价差约 17%",
      forms: ["IDE 插件（VS Code/JetBrains 等）", "CLI", "GitHub/GitLab 集成", "Google Cloud 控制台管理"],
      usageModel: "按席位订阅；个人免费层存在（本次快照页未含其额度数字）→ 待核实",
      plans: [
        { name: "Standard（月付）", audience: "团队", monthly: 22.8, annualMonthly: 19, annualUpfront: 228, minSeats: null, perSeat: true, purchasable: true,
          included: "面向企业与团队的 AI 辅助开发", overage: null, src: "gemini",
          annualNote: "年付 $19/席/月（需预付年约）；月付 $22.80/席/月" },
        { name: "Enterprise（月付）", audience: "团队", monthly: 54, annualMonthly: 45, annualUpfront: 540, minSeats: null, perSeat: true, purchasable: true,
          included: "Standard 全部 + 企业级能力（具体差异未在快照页展开）", overage: null, src: "gemini",
          annualNote: "年付 $45/席/月；月付 $54/席/月" },
      ],
      capabilities: {
        completion: { s: "full", note: "IDE 补全" },
        repoUnderstanding: { s: "full", note: "1M token 上下文（Gemini 3）" },
        multiFile: { s: "partial", note: "Agent 多文件能力未在快照页说明 → 待核实" },
        terminal: { s: "partial", note: "CLI 存在，细节待核实" },
        review: { s: "partial", note: "代码审查未在快照页说明 → 待核实" },
        cloudAgent: { s: "partial", note: "未在快照页说明 → 待核实" },
      },
      admin: {
        sso: { s: "ent", note: "随 Google Workspace/Cloud 身份体系" },
        audit: { s: "partial", note: "Google Cloud 审计能力存在；产品级审计未在快照页说明" },
        privacyMode: { s: "partial", note: "数据治理说明在 Google Cloud 政策中；快照页未摘录" },
        adminDashboard: { s: "full", note: "Google Cloud 控制台管理" },
      },
      recent90d: ["定价页确认 Gemini 3 与 1M token 上下文窗口作为当前卖点；Standard/Enterprise 月付与年付价差约 17%。"],
      calc: { teamPlan: "Standard", monthlyPrice: 22.8, annualMonthly: 19, minSeats: null, seatNote: "最低席位未在快照页核实" },
    },
  ],
  findings: [
    { text: "团队档价格带宽极宽：同为「基础团队订阅」，每人每月从 $19（Copilot Business）到 $40（Cursor Teams）相差 2.1 倍；50 人团队年成本差距可达 $12,600（按月付、仅席位费）。", weight: "high" },
    { text: "计费模式出现两条路线：固定席位订阅（Cursor/Copilot/Gemini/Windsurf）vs「席位费 + API 费率用量」（Claude Team/Enterprise、Windsurf 超额）。Claude 的混合模式意味着报表只能给出下限（席位费），实际总成本随用量上浮，采购时必须按用量建模。", weight: "high" },
    { text: "Windsurf 已并入 Cognition（Devin）：定价页以 Devin 品牌呈现，Teams 为 $80/月基础 + $40/席/月；采购合同主体与支持责任已变，需按 Cognition 重新评估。", weight: "high" },
    { text: "OpenAI 暂停 ChatGPT Pro $200 新注册（2026-09-10 公告）：个人重档无法新购，团队若依赖 Pro 档个人席位需改走 Business/Edu 询价，预算模型失去公开锚点。", weight: "high" },
    { text: "年付折扣普遍存在但口径不一：Gemini 年付省 17%（$22.80→$19）、Claude Pro 年付省 $4/月（$200 一次付）、Claude Team 省 $5/席/月；Cursor/Copilot/Windsurf 年付价未在快照页公开，不能假设有折扣。", weight: "medium" },
  ],
  recommendations: {
    individual: {
      title: "个人开发者",
      body: "以补全与轻量聊天为主：GitHub Copilot Pro（$10/月）是验证过的最低付费档，且免费档（2,000 补全+50 聊天/月）足够试水。以 Agent 日常开发为主：Cursor Pro（$20/月）或 Windsurf Pro（$20/月，含 Devin 云 Agent）。Claude Code 走 Claude Pro（$20/月，年付折合 $17/月）适合终端优先的工作流。Codex 可用 ChatGPT Plus（$20/月，价格待核实）但 Pro 档已停新购。",
      conditions: ["以上均为月付公开价；年付价以官方结账页为准", "Agent 重度用户请先试 5 天工作强度再决定是否上 $60-$200 档"],
      verify: ["Cursor/Copilot 年付价与折扣", "ChatGPT Plus 当前公开价", "各档 premium/credits 额度换算你的真实用量"],
    },
    smallTeam: {
      title: "小型团队（5-20 人）",
      body: "预算优先且要最成熟的协作治理：GitHub Copilot Business（$19/人/月）——许可与策略管理开箱即用。Agent 深度使用且要统一工作流：Cursor Teams（$40/人/月）含团队规则市场与 Bugbot。Google 生态且可年付：Gemini Code Assist Standard（年付 $19/人/月，与 Copilot Business 同价位）。混合模式注意：Claude Team Standard 年付 $20/席/月看似便宜，但用量按 API 费率另计，5 人团队需预留用量预算；Windsurf Teams 是 $80 基础 + $40/席，小团队摊薄后反而贵。",
      conditions: ["对比口径：仅含基础席位订阅费，不含超额用量", "Claude/Windsurf 为混合计费，实际成本随用量上升"],
      verify: ["Cursor Teams 与 Copilot Business 的年付价", "Claude Team 最低席位数与真实用量分布", "Windsurf Teams $80 基础费包含的席位"],
    },
    governedTeam: {
      title: "有管理要求的团队（SSO/审计/合规）",
      body: "治理最完整的是 GitHub Copilot Enterprise（$39/人/月）——代码库索引 + 组织策略 + IP 赔偿，且审计随 GitHub Enterprise 体系。需要集中身份与审计的 Claude 团队应选 Claude Enterprise（$20/席/月 + API 用量，含 SCIM/审计日志/RBAC）。Cursor 大组织需求（发票、池化用量、SCIM）走 Teams Premium 或 Enterprise（需询价）。Windsurf/Gemini 的审计与 SSO 说明在快照中不完整，采购前必须索取安全白皮书。",
      conditions: ["「企业级 SSO/审计」多数在最高档而非团队档，逐项核对功能表", "混合计费工具（Claude）必须把用量费纳入预算审批"],
      verify: ["各家 SSO/SCIM/审计日志的具体档位归属", "数据保留与训练政策的法律文本", "Claude Enterprise 的 $20/席是否含最低承诺消费"],
    },
  },
};
if (typeof module !== "undefined") module.exports = REPORT;
